2023_qrack_raid_0 blog post
unitaryfund/unitary.fund pull request #428
Opened 2023-12-26 00:21 UTC by WrathfulSpatula

This is the blog post about Qrack's frontier experiments in recreating something equivalent to 2019 Sycamore (or universal random circuit sampling in general) requested by Will.

(Merry Christmas, and Happy Holidays! This is low priority, but I stole a few minutes for it during our family's celebrations. See you in 2024!)

2024-02-05 11:33 UTC, nathanshammah requested changes
Thanks @WrathfulSpatula and sorry this has taken so long. I update the date: can you please also update the title of the file to 2024? 

I made some initial comments. My feedback is a bit of summarizing/cutting text, if possible could help, together with some introductory subtitles along the way.

2024-02-05 11:33 UTC, nathanshammah commented on src/content/blog/2023_qrack_raid_0.md
> +year: 2023
```suggestion
day: 5
month: 2
year: 2024
```

2024-02-05 11:33 UTC, nathanshammah commented on src/content/blog/2023_qrack_raid_0.md
> +IBM was likely the first to point out, after the 2019 Sycamore universal random circuit sampling experiments, that disk storage could be employed to increase effective RAM limits of quantum computer
```suggestion
IBM was likely the first to [point out](https://research.ibm.com/blog/on-quantum-supremacy), after the 2019 Sycamore universal random circuit sampling experiments, that disk storage could be employed to increase effective RAM limits of quantum computer simulation far past what is attainable with GPU and “DIMMs” (RAM boards inserted into your computer motherboard). Roughly, the largest supercomputers in the world, even arrayed together, might only have DRAM capacity for about 49 or 50 qubits of state vector simulation, aside from other techniques like tensor networks or any approximate simulation techniques. (Just as with your personal computer hardware, adding 1 qubit _doubles_ the necessary memory footprint, and the capacity of the largest supercomputers in the world, today, does not double in negligible time, effort, or cost!) However, disk storage can be _nearly_ as good as “DIMMs,” but drastically cheaper and far easier to scale to terabyte-range and past!
```

2024-02-05 11:33 UTC, nathanshammah commented on src/content/blog/2023_qrack_raid_0.md
> +The obvious problem is that data transfer to and from disk is _far_ slower than “DIMMs.” Ultimately, “swap disk” as (random-access) memory needs to somehow be made fast enough to keep up with the pro
Add link? Suggestions: arXiv report and or previous blog post on Qrack white paper.

2024-02-05 11:33 UTC, nathanshammah commented on src/content/blog/2023_qrack_raid_0.md
> +IBM was likely the first to point out, after the 2019 Sycamore universal random circuit sampling experiments, that disk storage could be employed to increase effective RAM limits of quantum computer
Also, can you spell out once the exact words for the acronym DIMMs?

2024-02-05 11:33 UTC, nathanshammah commented on src/content/blog/2023_qrack_raid_0.md
> +At 32-bit floating point precision (with 64-bit complex numbers), 32 *giga*bytes of memory will fit 32 qubits worth of state vector simulation. For each additional qubit desired, you need to _double_
This post start is already very technical. Is there a way to make it a bit more gentle for non experts?

One suggestion would be to repeat the question of the title, with a bit more context. For example, something like: ```
There is a fast pace in the qubit count growth of experiments on quantum computers. At the same time, there is a growing literature of classical simulation (_add links_) of such experiments, often involving approximate methods and high performance computing (HPC) resources. One could thus be wondering: 

_What is the limit of what can be achieved on a personal computer/with moderate cloud resources?_

In this blog post we provide a possible recipe to this answer, showing how to build a ~40 qubit simulator for less than $3000. 
```

Still, even with this preamble, I feel like the current initial text starts a bit technical. Could you maybe provide a bit of context on how to do the resource estimation, without introducing immediately technical jargon? That could help a lot!

2024-02-05 11:33 UTC, nathanshammah commented on src/content/blog/2023_qrack_raid_0.md
> +When using the Qrack gate-based quantum computer simulator library, we officially suggest 64-bit “double” precision (with 128-bit complex numbers) when state vector simulation will exceed about 32 qu
Please add a link to Qrack.

2024-02-05 11:33 UTC, nathanshammah commented on src/content/blog/2023_qrack_raid_0.md
> +You can experiment with your own Qrack benchmarks, but, if you’re looking for a ready-made case of universal random circuit sampling similar to 2019 Sycamore, check out the case “test_noisy_fidelity_
please add relevant link.

2024-02-10 05:07 UTC, KallieFerguson commented
Happy to see there's movement here! If this gets published next week could you send a note to Frances so she can share on socials? 

I see it also wishes people happy holidays at the end, we might want to change that now that it's February!

2024-10-24 21:59 UTC, closed without merging

2024-11-19 18:44 UTC, amirebrahimi commented
@WrathfulSpatula, how come you decided not to post this? The draft was fun to read though. I appreciate the details of the build-out.