Create 2023_Q4.md
unitaryfund/unitary.fund pull request #435
Opened 2024-01-30 00:22 UTC by KallieFerguson

Q4 recap blog

2024-02-01 09:43 UTC, nathanshammah requested changes

2024-02-01 09:43 UTC, nathanshammah commented on src/content/blog/2023_Q4.md
> +author: Will Zheng
```suggestion
author: Will Zeng
```

2024-02-01 09:49 UTC, nathanshammah commented
@KallieFerguson I suggest removing most text and pushing small incremental bits in sequential commits to see when the tests start failing.

2024-02-01 21:32 UTC, KallieFerguson commented
Ok I think it's passing all the checks now! @nathanshammah

2024-02-02 15:24 UTC, nathanshammah approved these changes

2024-02-02 15:24 UTC, nathanshammah commented on src/content/blog/2023_Q4.md
> +# Unitary Fund Q4 2023 Update: UnitaryCON, 2023 QOSS Survey results, new grants and project updates
```suggestion
```

2024-02-02 15:25 UTC, nathanshammah commented on src/content/blog/2023_Q4.md
> +# Unitary Fund Q4 2023 Update: UnitaryCON, 2023 QOSS Survey results, new grants and project updates
removing repeated title, as the title of the top is already shown

2024-02-02 18:17 UTC, merged