Update index.mdx
unitaryfund/unitary.fund pull request #624
Opened 2024-11-01 22:31 UTC by KallieFerguson

Add nathan Xanadu quote

2024-11-01 22:35 UTC, cosenal approved these changes

2024-11-04 13:38 UTC, beecastanon commented
@KallieFerguson there's an extra quotation mark at the beginning of the new quote. Please remove and I'll go ahead and merge it after. Thanks for grabbing the new quote!

2024-11-04 13:49 UTC, cosenal requested changes
whatever @beecastanon said :)

2024-11-04 16:19 UTC, KallieFerguson commented
@beecastanon fixed.

2024-11-04 17:20 UTC, cosenal approved these changes

2024-11-04 17:32 UTC, merged